"""Test asdex sparsity detection against CUTEst ground truth via sif2jax.

These tests compare asdex's detected sparsity patterns against
ground truth from CUTEst benchmark problems.
The goal is to catalog conservativeness — where asdex over-estimates sparsity.

Fixtures are generated by ``tests/setup/generate_cutest_fixtures.py``.
"""

from __future__ import annotations

import warnings
from pathlib import Path

import numpy as np
import pytest

sif2jax = pytest.importorskip("sif2jax")

import asdex  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "cutest_fixtures"


def _discover_fixtures(kind: str) -> list[str]:
    """Discover fixture problem names by globbing the fixture directory."""
    subdir = FIXTURE_DIR / kind
    if not subdir.exists():
        return []
    return sorted(p.stem for p in subdir.glob("*.npz"))


def _find_problem(problems, name: str):
    """Find a sif2jax problem by name, or None if not found."""
    for p in problems:
        if p.name == name:
            return p
    return None


def _assert_superset(
    detected: np.ndarray,
    ground_truth: np.ndarray,
    name: str,
    kind: str,
):
    """Assert detected is a superset of ground truth, warn on extras.

    Args:
        detected: Dense boolean array from asdex detection.
        ground_truth: Dense boolean array from ground truth.
        name: Problem name for error messages.
        kind: Pattern kind (hessian, jacobian_eq, jacobian_ineq).
    """
    # Hard assertion: no false negatives.
    missed = ground_truth & ~detected
    assert not missed.any(), (
        f"{kind}/{name}: asdex missed {missed.sum()} nonzeros (false negatives)!\n"
        f"  Ground truth nnz: {ground_truth.sum()}\n"
        f"  Detected nnz: {detected.sum()}\n"
        f"  Missed: {missed.sum()}"
    )

    # Warn on conservativeness (extra nonzeros).
    extras = detected & ~ground_truth
    if extras.any():
        total = detected.shape[0] * detected.shape[1]
        warnings.warn(
            f"{kind}/{name}: asdex detected {extras.sum()} extra nonzeros "
            f"(detected={detected.sum()}, truth={ground_truth.sum()}, "
            f"density: {detected.sum() / total:.1%} vs {ground_truth.sum() / total:.1%})",
            stacklevel=2,
        )


# Hessian tests

hessian_names = _discover_fixtures("hessian")


@pytest.mark.slow
@pytest.mark.cutest
@pytest.mark.hessian
@pytest.mark.parametrize("name", hessian_names)
def test_hessian_sparsity_cutest(name):
    """Compare asdex Hessian sparsity against CUTEst ground truth."""
    problem = _find_problem(sif2jax.unconstrained_minimisation_problems, name)
    if problem is None:
        pytest.skip(f"{name} not available in sif2jax")

    gt = asdex.SparsityPattern.load(FIXTURE_DIR / "hessian" / f"{name}.npz")
    y0 = problem.y0
    args = problem.args

    if y0.size != gt.shape[0]:
        pytest.skip(
            f"{name}: shape mismatch (sif2jax n={y0.size}, fixture n={gt.shape[0]})"
        )

    def f(y):
        return problem.objective(y, args)

    try:
        detected = asdex.hessian_sparsity(f, y0.shape)
    except (NotImplementedError, IndexError, ValueError) as exc:
        pytest.xfail(f"asdex internal error for {name}: {exc}")

    _assert_superset(
        detected.todense().astype(bool),
        gt.todense().astype(bool),
        name,
        "hessian",
    )


# Jacobian equality constraint tests

jacobian_eq_names = _discover_fixtures("jacobian_eq")


@pytest.mark.slow
@pytest.mark.cutest
@pytest.mark.jacobian
@pytest.mark.parametrize("name", jacobian_eq_names)
def test_jacobian_eq_sparsity_cutest(name):
    """Compare asdex Jacobian sparsity for equality constraints against ground truth."""
    problem = _find_problem(sif2jax.constrained_minimisation_problems, name)
    if problem is None:
        pytest.skip(f"{name} not available in sif2jax")

    gt = asdex.SparsityPattern.load(FIXTURE_DIR / "jacobian_eq" / f"{name}.npz")

    def f(y):
        return problem.constraint(y)[0]

    try:
        detected = asdex.jacobian_sparsity(f, problem.y0.shape)
    except (NotImplementedError, IndexError, ValueError) as exc:
        pytest.xfail(f"asdex internal error for {name}: {exc}")

    _assert_superset(
        detected.todense().astype(bool),
        gt.todense().astype(bool),
        name,
        "jacobian_eq",
    )


# Jacobian inequality constraint tests

jacobian_ineq_names = _discover_fixtures("jacobian_ineq")


@pytest.mark.slow
@pytest.mark.cutest
@pytest.mark.jacobian
@pytest.mark.parametrize("name", jacobian_ineq_names)
def test_jacobian_ineq_sparsity_cutest(name):
    """Compare asdex Jacobian sparsity for inequality constraints against ground truth."""
    problem = _find_problem(sif2jax.constrained_minimisation_problems, name)
    if problem is None:
        pytest.skip(f"{name} not available in sif2jax")

    gt = asdex.SparsityPattern.load(FIXTURE_DIR / "jacobian_ineq" / f"{name}.npz")

    def f(y):
        return problem.constraint(y)[1]

    try:
        detected = asdex.jacobian_sparsity(f, problem.y0.shape)
    except (NotImplementedError, IndexError, ValueError) as exc:
        pytest.xfail(f"asdex internal error for {name}: {exc}")

    _assert_superset(
        detected.todense().astype(bool),
        gt.todense().astype(bool),
        name,
        "jacobian_ineq",
    )
