"""Test asdex sparsity detection against CUTEst ground truth via sif2jax.

These tests compare asdex's detected sparsity patterns against
ground truth from CUTEst benchmark problems.
The goal is to catalog conservativeness — where asdex over-estimates sparsity.

Fixtures are generated by ``tests/setup/generate_cutest_fixtures.py``.
"""

from __future__ import annotations

import warnings
from pathlib import Path

import numpy as np
import pytest

sif2jax = pytest.importorskip("sif2jax")

import asdex  # noqa: E402

FIXTURE_DIR = Path(__file__).parent / "cutest_fixtures"

# Expected (detected_nnz, target_nnz) for each CUTEst problem.
# When a handler improvement reduces detected nnz,
# update the corresponding value here.
EXPECTED_NNZ: dict[str, tuple[int, int]] = {
    "hessian/AKIVA": (4, 4),
    "hessian/ALLINITU": (16, 6),
    "hessian/ARGLINA": (40000, 200),
    "hessian/ARGLINB": (40000, 40000),
    "hessian/ARGLINC": (39204, 39204),
    "hessian/ARGTRIGLS": (40000, 40000),
    "hessian/BARD": (9, 9),
    "hessian/BEALE": (4, 3),
    "hessian/BENNETT5LS": (9, 9),
    "hessian/BIGGS6": (36, 36),
    "hessian/BOX3": (9, 9),
    "hessian/BOXBODLS": (4, 4),
    "hessian/BROWNBS": (4, 2),
    "hessian/BROWNDEN": (16, 16),
    "hessian/CHNROSNB": (148, 148),
    "hessian/CHNRSNBM": (148, 148),
    "hessian/CHWIRUT1LS": (9, 9),
    "hessian/CHWIRUT2LS": (9, 9),
    "hessian/CLIFF": (4, 4),
    "hessian/CLUSTERLS": (4, 2),
    "hessian/COATING": (17956, 2300),
    "hessian/COOLHANSLS": (81, 39),
    "hessian/CUBE": (4, 4),
    "hessian/DANIWOODLS": (4, 4),
    "hessian/DENSCHNA": (4, 4),
    "hessian/DENSCHNB": (4, 4),
    "hessian/DENSCHNC": (4, 4),
    "hessian/DENSCHND": (9, 9),
    "hessian/DENSCHNE": (3, 3),
    "hessian/DENSCHNF": (4, 4),
    "hessian/DEVGLA1": (16, 16),
    "hessian/DEVGLA2": (25, 25),
    "hessian/DIXMAANA1": (9, 9),
    "hessian/DJTL": (4, 4),
    "hessian/DMN15102LS": (4356, 4356),
    "hessian/DMN15103LS": (9801, 9801),
    "hessian/EGGCRATE": (2, 2),
    "hessian/ELATVIDU": (4, 4),
    "hessian/ENGVAL2": (9, 9),
    "hessian/ERRINROS": (2500, 148),
    "hessian/EXP2": (4, 4),
    "hessian/EXPFIT": (4, 3),
    "hessian/GAUSS1LS": (64, 64),
    "hessian/GAUSS2LS": (64, 64),
    "hessian/GAUSS3LS": (64, 64),
    "hessian/GAUSSIAN": (9, 5),
    "hessian/GENROSE": (250000, 1498),
    "hessian/GROWTHLS": (9, 9),
    "hessian/HAHN1LS": (49, 49),
    "hessian/HAIRY": (4, 4),
    "hessian/HATFLDD": (9, 9),
    "hessian/HATFLDE": (9, 9),
    "hessian/HATFLDFL": (9, 9),
    "hessian/HATFLDFLS": (9, 9),
    "hessian/HEART6LS": (36, 20),
    "hessian/HEART8LS": (64, 32),
    "hessian/HELIX": (9, 7),
    "hessian/HILBERTA": (4, 4),
    "hessian/HILBERTB": (100, 100),
    "hessian/HIMMELBCLS": (4, 4),
    "hessian/HIMMELBG": (4, 4),
    "hessian/HIMMELBH": (2, 1),
    "hessian/HUMPS": (4, 4),
    "hessian/JENSMP": (4, 4),
    "hessian/JUDGE": (4, 4),
    "hessian/KIRBY2LS": (25, 25),
    "hessian/KOWOSB": (16, 16),
    "hessian/LANCZOS1LS": (36, 36),
    "hessian/LANCZOS2LS": (36, 36),
    "hessian/LOGHAIRY": (4, 4),
    "hessian/LSC1LS": (9, 9),
    "hessian/LSC2LS": (9, 9),
    "hessian/LUKSAN11LS": (298, 298),
    "hessian/LUKSAN12LS": (484, 484),
    "hessian/LUKSAN13LS": (484, 482),
    "hessian/LUKSAN14LS": (420, 420),
    "hessian/LUKSAN15LS": (592, 592),
    "hessian/LUKSAN16LS": (592, 592),
    "hessian/LUKSAN17LS": (10000, 592),
    "hessian/LUKSAN21LS": (10000, 494),
    "hessian/MARATOSB": (4, 4),
    "hessian/MEXHAT": (4, 4),
    "hessian/MGH09LS": (16, 16),
    "hessian/MGH10LS": (9, 9),
    "hessian/MGH10SLS": (9, 9),
    "hessian/MGH17LS": (25, 25),
    "hessian/MGH17SLS": (25, 19),
    "hessian/MISRA1ALS": (4, 4),
    "hessian/MISRA1BLS": (4, 4),
    "hessian/MISRA1CLS": (4, 4),
    "hessian/MISRA1DLS": (4, 4),
    "hessian/NELSONLS": (9, 9),
    "hessian/OSBORNEA": (25, 25),
    "hessian/OSBORNEB": (121, 117),
    "hessian/PALMER1C": (64, 64),
    "hessian/PALMER1D": (49, 49),
    "hessian/PALMER2C": (64, 64),
    "hessian/PALMER3C": (64, 64),
    "hessian/PALMER4C": (64, 64),
    "hessian/PALMER5C": (36, 36),
    "hessian/PALMER5D": (16, 16),
    "hessian/PALMER6C": (64, 64),
    "hessian/PALMER7C": (64, 64),
    "hessian/PALMER8C": (64, 64),
    "hessian/PENALTY3": (40000, 40000),
    "hessian/PRICE3": (4, 4),
    "hessian/PRICE4": (4, 4),
    "hessian/QING": (100, 99),
    "hessian/RAT42LS": (9, 9),
    "hessian/RAT43LS": (16, 16),
    "hessian/ROSENBR": (4, 4),
    "hessian/ROSZMAN1LS": (16, 16),
    "hessian/S308": (4, 4),
    "hessian/SISSER": (4, 4),
    "hessian/SNAIL": (4, 4),
    "hessian/SPIN2LS": (10404, 10389),
    "hessian/TRIGON1": (100, 100),
    "hessian/VANDANMSLS": (484, 16),
    "hessian/VARDIM": (40000, 40000),
    "hessian/VESUVIALS": (64, 46),
    "hessian/VESUVIOLS": (64, 46),
    "hessian/VESUVIOULS": (64, 42),
    "hessian/VIBRBEAM": (64, 64),
    "hessian/WAYSEA1": (4, 4),
    "hessian/WAYSEA2": (4, 4),
    "hessian/ZANGWIL2": (4, 4),
    "jacobian_eq/ALSOTAME": (2, 2),
    "jacobian_eq/BATCH": (54, 48),
    "jacobian_eq/BT10": (4, 4),
    "jacobian_eq/BT11": (8, 8),
    "jacobian_eq/BT12": (8, 7),
    "jacobian_eq/BT3": (7, 7),
    "jacobian_eq/BT4": (6, 6),
    "jacobian_eq/BT5": (6, 6),
    "jacobian_eq/BT6": (5, 5),
    "jacobian_eq/BT7": (8, 8),
    "jacobian_eq/BT8": (6, 4),
    "jacobian_eq/BT9": (6, 6),
    "jacobian_eq/BYRDSPHR": (6, 6),
    "jacobian_eq/CSFI1": (7, 7),
    "jacobian_eq/CSFI2": (7, 7),
    "jacobian_eq/DALLASS": (92, 92),
    "jacobian_eq/DECONVC": (11, 11),
    "jacobian_eq/DEGENLPA": (82, 82),
    "jacobian_eq/DEGENLPB": (82, 82),
    "jacobian_eq/DEGENQP": (10, 10),
    "jacobian_eq/DEGENQPC": (50, 50),
    "jacobian_eq/DUAL1": (85, 85),
    "jacobian_eq/DUAL2": (96, 96),
    "jacobian_eq/DUAL3": (111, 111),
    "jacobian_eq/DUAL4": (75, 75),
    "jacobian_eq/DUALC1": (9, 9),
    "jacobian_eq/DUALC2": (7, 7),
    "jacobian_eq/DUALC5": (8, 8),
    "jacobian_eq/DUALC8": (8, 8),
    "jacobian_eq/FLETCHER": (4, 0),
    "jacobian_eq/FLT": (2, 2),
    "jacobian_eq/GOULDQP1": (56, 56),
    "jacobian_eq/HIMMELBC": (4, 4),
    "jacobian_eq/HIMMELBD": (4, 4),
    "jacobian_eq/HIMMELBE": (5, 5),
    "jacobian_eq/HS107": (34, 34),
    "jacobian_eq/HS111": (14, 14),
    "jacobian_eq/HS111LNP": (14, 14),
    "jacobian_eq/HS112": (14, 14),
    "jacobian_eq/HS114": (11, 11),
    "jacobian_eq/HS119": (53, 53),
    "jacobian_eq/HS32": (3, 3),
    "jacobian_eq/HS39": (6, 6),
    "jacobian_eq/HS40": (7, 7),
    "jacobian_eq/HS41": (4, 4),
    "jacobian_eq/HS42": (3, 3),
    "jacobian_eq/HS46": (6, 6),
    "jacobian_eq/HS47": (8, 8),
    "jacobian_eq/HS48": (8, 8),
    "jacobian_eq/HS49": (6, 6),
    "jacobian_eq/HS50": (9, 9),
    "jacobian_eq/HS51": (7, 7),
    "jacobian_eq/HS52": (7, 7),
    "jacobian_eq/HS53": (7, 7),
    "jacobian_eq/HS54": (2, 2),
    "jacobian_eq/HS55": (15, 15),
    "jacobian_eq/HS56": (10, 10),
    "jacobian_eq/HS60": (3, 3),
    "jacobian_eq/HS61": (4, 2),
    "jacobian_eq/HS62": (3, 3),
    "jacobian_eq/HS63": (6, 6),
    "jacobian_eq/HS68": (4, 4),
    "jacobian_eq/HS69": (4, 4),
    "jacobian_eq/HS71": (4, 4),
    "jacobian_eq/HS73": (4, 4),
    "jacobian_eq/HS77": (6, 6),
    "jacobian_eq/HS78": (11, 11),
    "jacobian_eq/HS79": (8, 8),
    "jacobian_eq/HS8": (4, 4),
    "jacobian_eq/HS80": (11, 11),
    "jacobian_eq/HS81": (11, 11),
    "jacobian_eq/HS87": (15, 15),
    "jacobian_eq/LSNNODOC": (10, 10),
    "jacobian_eq/MARATOS": (2, 2),
    "jacobian_eq/MSS1": (6570, 378),
    "jacobian_eq/NASH": (157, 157),
    "jacobian_eq/ODFITS": (15, 15),
    "jacobian_eq/OPTCNTRL": (70, 70),
    "jacobian_eq/ORTHREGB": (72, 72),
    "jacobian_eq/PORTFL1": (12, 12),
    "jacobian_eq/PORTFL2": (12, 12),
    "jacobian_eq/PORTFL3": (12, 12),
    "jacobian_eq/PORTFL4": (12, 12),
    "jacobian_eq/PORTFL6": (12, 12),
    "jacobian_eq/S316-322": (2, 0),
    "jacobian_eq/TAME": (2, 2),
    "jacobian_eq/TENBARS1": (62, 0),
    "jacobian_eq/TENBARS2": (62, 0),
    "jacobian_eq/TENBARS3": (62, 0),
    "jacobian_eq/TENBARS4": (62, 0),
    "jacobian_eq/TRO11X3": (9000, 446),
    "jacobian_eq/TRO3X3": (360, 62),
    "jacobian_eq/TRO4X4": (1512, 178),
    "jacobian_eq/TRO5X5": (4320, 298),
    "jacobian_eq/TRO6X2": (900, 114),
    "jacobian_ineq/AVGASA": (30, 30),
    "jacobian_ineq/AVGASB": (30, 30),
    "jacobian_ineq/BATCH": (130, 130),
    "jacobian_ineq/BIGGSC4": (16, 16),
    "jacobian_ineq/BURKEHAN": (1, 1),
    "jacobian_ineq/CANTILVR": (5, 5),
    "jacobian_ineq/CB2": (9, 7),
    "jacobian_ineq/CB3": (9, 7),
    "jacobian_ineq/CHACONN1": (9, 9),
    "jacobian_ineq/CHACONN2": (9, 7),
    "jacobian_ineq/CLEUVEN7": (35948, 35948),
    "jacobian_ineq/CSFI1": (4, 4),
    "jacobian_ineq/CSFI2": (4, 4),
    "jacobian_ineq/DEGENQP": (360, 360),
    "jacobian_ineq/DEGENQPC": (58800, 58800),
    "jacobian_ineq/DEMBO7": (68, 68),
    "jacobian_ineq/DEMYMALO": (9, 9),
    "jacobian_ineq/DIPIGRI": (19, 17),
    "jacobian_ineq/DUALC1": (1926, 1926),
    "jacobian_ineq/DUALC2": (1596, 1596),
    "jacobian_ineq/DUALC5": (2216, 2216),
    "jacobian_ineq/DUALC8": (4016, 4016),
    "jacobian_ineq/ELATTAR": (708, 706),
    "jacobian_ineq/FLETCHER": (6, 6),
    "jacobian_ineq/GIGOMEZ1": (9, 9),
    "jacobian_ineq/GIGOMEZ2": (9, 7),
    "jacobian_ineq/GIGOMEZ3": (9, 7),
    "jacobian_ineq/GOFFIN": (2550, 2550),
    "jacobian_ineq/HAIFAM": (12750, 711),
    "jacobian_ineq/HAIFAS": (31, 18),
    "jacobian_ineq/HATFLDH": (16, 16),
    "jacobian_ineq/HS100": (19, 17),
    "jacobian_ineq/HS101": (31, 31),
    "jacobian_ineq/HS102": (31, 31),
    "jacobian_ineq/HS103": (31, 31),
    "jacobian_ineq/HS104": (17, 17),
    "jacobian_ineq/HS105": (2, 2),
    "jacobian_ineq/HS106": (17, 17),
    "jacobian_ineq/HS108": (39, 19),
    "jacobian_ineq/HS113": (32, 29),
    "jacobian_ineq/HS114": (20, 20),
    "jacobian_ineq/HS116": (43, 43),
    "jacobian_ineq/HS117": (62, 62),
    "jacobian_ineq/HS15": (4, 4),
    "jacobian_ineq/HS16": (4, 4),
    "jacobian_ineq/HS17": (4, 4),
    "jacobian_ineq/HS18": (4, 4),
    "jacobian_ineq/HS19": (4, 4),
    "jacobian_ineq/HS20": (6, 6),
    "jacobian_ineq/HS21": (2, 2),
    "jacobian_ineq/HS21MOD": (2, 2),
    "jacobian_ineq/HS22": (4, 4),
    "jacobian_ineq/HS23": (10, 10),
    "jacobian_ineq/HS24": (6, 6),
    "jacobian_ineq/HS268": (25, 25),
    "jacobian_ineq/HS30": (2, 2),
    "jacobian_ineq/HS31": (2, 2),
    "jacobian_ineq/HS32": (3, 3),
    "jacobian_ineq/HS33": (6, 2),
    "jacobian_ineq/HS34": (4, 4),
    "jacobian_ineq/HS35": (3, 3),
    "jacobian_ineq/HS35I": (3, 3),
    "jacobian_ineq/HS35MOD": (3, 3),
    "jacobian_ineq/HS36": (3, 3),
    "jacobian_ineq/HS37": (6, 6),
    "jacobian_ineq/HS43": (12, 9),
    "jacobian_ineq/HS44": (12, 12),
    "jacobian_ineq/HS44NEW": (12, 12),
    "jacobian_ineq/HS57": (2, 2),
    "jacobian_ineq/HS64": (3, 3),
    "jacobian_ineq/HS65": (3, 2),
    "jacobian_ineq/HS66": (4, 4),
    "jacobian_ineq/HS71": (4, 4),
    "jacobian_ineq/HS72": (8, 8),
    "jacobian_ineq/HS73": (8, 8),
    "jacobian_ineq/HS76": (10, 10),
    "jacobian_ineq/HS76I": (10, 10),
    "jacobian_ineq/HS83": (13, 13),
    "jacobian_ineq/HS86": (37, 37),
    "jacobian_ineq/HS88": (2, 2),
    "jacobian_ineq/HS89": (3, 3),
    "jacobian_ineq/HS90": (4, 4),
    "jacobian_ineq/HS93": (12, 12),
    "jacobian_ineq/HS95": (20, 20),
    "jacobian_ineq/HS96": (20, 20),
    "jacobian_ineq/HS97": (20, 20),
    "jacobian_ineq/HS98": (20, 20),
    "jacobian_ineq/LOOTSMA": (6, 6),
    "jacobian_ineq/LSQFIT": (2, 2),
    "jacobian_ineq/MADSEN": (14, 14),
    "jacobian_ineq/MAKELA1": (6, 6),
    "jacobian_ineq/MAKELA2": (9, 8),
    "jacobian_ineq/MAKELA3": (40, 40),
    "jacobian_ineq/MAKELA4": (80, 80),
    "jacobian_ineq/MATRIX2": (6, 6),
    "jacobian_ineq/MINMAXBD": (100, 100),
    "jacobian_ineq/MINMAXRB": (10, 10),
    "jacobian_ineq/OET1": (3006, 3004),
    "jacobian_ineq/OET2": (3006, 2004),
    "jacobian_ineq/OET3": (4008, 4004),
    "jacobian_ineq/OET4": (4008, 3004),
    "jacobian_ineq/OET5": (5010, 5010),
    "jacobian_ineq/OET6": (5010, 3006),
    "jacobian_ineq/OET7": (7014, 4008),
    "jacobian_ineq/OPTPRLOC": (170, 170),
    "jacobian_ineq/PENTAGON": (30, 27),
    "jacobian_ineq/POLAK1": (6, 6),
    "jacobian_ineq/POLAK2": (22, 22),
    "jacobian_ineq/POLAK3": (120, 120),
    "jacobian_ineq/POLAK4": (9, 9),
    "jacobian_ineq/POLAK5": (6, 6),
    "jacobian_ineq/POLAK6": (20, 20),
    "jacobian_ineq/S365": (22, 16),
    "jacobian_ineq/S365MOD": (22, 16),
    "jacobian_ineq/SIMPLLPA": (4, 4),
    "jacobian_ineq/SIMPLLPB": (6, 6),
    "jacobian_ineq/SIPOW1": (4000, 3996),
    "jacobian_ineq/SIPOW2": (3000, 2996),
    "jacobian_ineq/TENBARS1": (2, 2),
    "jacobian_ineq/TENBARS4": (2, 2),
    "jacobian_ineq/TRO11X3": (90, 90),
    "jacobian_ineq/TRO3X3": (18, 18),
    "jacobian_ineq/TRO4X4": (39, 39),
    "jacobian_ineq/TRO5X5": (68, 68),
    "jacobian_ineq/TRO6X2": (25, 25),
    "jacobian_ineq/ZECEVIC2": (4, 4),
    "jacobian_ineq/ZECEVIC3": (4, 4),
    "jacobian_ineq/ZECEVIC4": (4, 4),
}


def _discover_fixtures(kind: str) -> list[str]:
    """Discover fixture problem names by globbing the fixture directory."""
    subdir = FIXTURE_DIR / kind
    if not subdir.exists():
        return []
    return sorted(p.stem for p in subdir.glob("*.npz"))


def _find_problem(problems, name: str):
    """Find a sif2jax problem by name, or None if not found."""
    for p in problems:
        if p.name == name:
            return p
    return None


def _assert_superset(
    detected: np.ndarray,
    ground_truth: np.ndarray,
    name: str,
    kind: str,
):
    """Assert detected is a superset of ground truth, warn on extras.

    Args:
        detected: Dense boolean array from asdex detection.
        ground_truth: Dense boolean array from ground truth.
        name: Problem name for error messages.
        kind: Pattern kind (hessian, jacobian_eq, jacobian_ineq).
    """
    # Hard assertion: no false negatives.
    missed = ground_truth & ~detected
    assert not missed.any(), (
        f"{kind}/{name}: asdex missed {missed.sum()} nonzeros (false negatives)!\n"
        f"  Ground truth nnz: {ground_truth.sum()}\n"
        f"  Detected nnz: {detected.sum()}\n"
        f"  Missed: {missed.sum()}"
    )

    # Warn on conservativeness (extra nonzeros).
    extras = detected & ~ground_truth
    if extras.any():
        total = detected.shape[0] * detected.shape[1]
        warnings.warn(
            f"{kind}/{name}: asdex detected {extras.sum()} extra nonzeros "
            f"(detected={detected.sum()}, truth={ground_truth.sum()}, "
            f"density: {detected.sum() / total:.1%} vs {ground_truth.sum() / total:.1%})",
            stacklevel=2,
        )


def _check_baseline(detected_nnz: int, name: str, kind: str):
    """Fail on nnz regressions or improvements so baselines stay current."""
    key = f"{kind}/{name}"
    expected = EXPECTED_NNZ.get(key)
    if expected is None:
        return
    expected_nnz, _ = expected
    if detected_nnz > expected_nnz:
        pytest.fail(
            f"{key}: REGRESSION — detected nnz increased "
            f"from {expected_nnz} to {detected_nnz}"
        )
    if detected_nnz < expected_nnz:
        pytest.fail(
            f"{key}: IMPROVEMENT — detected nnz decreased "
            f"from {expected_nnz} to {detected_nnz}. "
            f"Update EXPECTED_NNZ[{key!r}] to ({detected_nnz}, {expected[1]})."
        )


# Hessian tests

hessian_names = _discover_fixtures("hessian")


@pytest.mark.slow
@pytest.mark.cutest
@pytest.mark.hessian
@pytest.mark.parametrize("name", hessian_names)
def test_hessian_sparsity_cutest(name):
    """Compare asdex Hessian sparsity against CUTEst ground truth."""
    problem = _find_problem(sif2jax.unconstrained_minimisation_problems, name)
    if problem is None:
        pytest.skip(f"{name} not available in sif2jax")

    gt = asdex.SparsityPattern.load(FIXTURE_DIR / "hessian" / f"{name}.npz")
    y0 = problem.y0
    args = problem.args

    if y0.size != gt.shape[0]:
        pytest.skip(
            f"{name}: shape mismatch (sif2jax n={y0.size}, fixture n={gt.shape[0]})"
        )

    def f(y):
        return problem.objective(y, args)

    try:
        detected = asdex.hessian_sparsity(f, y0.shape)
    except (NotImplementedError, IndexError, ValueError) as exc:
        pytest.xfail(f"asdex internal error for {name}: {exc}")

    _assert_superset(
        detected.todense().astype(bool),
        gt.todense().astype(bool),
        name,
        "hessian",
    )
    _check_baseline(detected.nnz, name, "hessian")


# Jacobian equality constraint tests

jacobian_eq_names = _discover_fixtures("jacobian_eq")


@pytest.mark.slow
@pytest.mark.cutest
@pytest.mark.jacobian
@pytest.mark.parametrize("name", jacobian_eq_names)
def test_jacobian_eq_sparsity_cutest(name):
    """Compare asdex Jacobian sparsity for equality constraints against ground truth."""
    problem = _find_problem(sif2jax.constrained_minimisation_problems, name)
    if problem is None:
        pytest.skip(f"{name} not available in sif2jax")

    gt = asdex.SparsityPattern.load(FIXTURE_DIR / "jacobian_eq" / f"{name}.npz")

    def f(y):
        return problem.constraint(y)[0]

    try:
        detected = asdex.jacobian_sparsity(f, problem.y0.shape)
    except (NotImplementedError, IndexError, ValueError) as exc:
        pytest.xfail(f"asdex internal error for {name}: {exc}")

    _assert_superset(
        detected.todense().astype(bool),
        gt.todense().astype(bool),
        name,
        "jacobian_eq",
    )
    _check_baseline(detected.nnz, name, "jacobian_eq")


# Jacobian inequality constraint tests

jacobian_ineq_names = _discover_fixtures("jacobian_ineq")


@pytest.mark.slow
@pytest.mark.cutest
@pytest.mark.jacobian
@pytest.mark.parametrize("name", jacobian_ineq_names)
def test_jacobian_ineq_sparsity_cutest(name):
    """Compare asdex Jacobian sparsity for inequality constraints against ground truth."""
    problem = _find_problem(sif2jax.constrained_minimisation_problems, name)
    if problem is None:
        pytest.skip(f"{name} not available in sif2jax")

    gt = asdex.SparsityPattern.load(FIXTURE_DIR / "jacobian_ineq" / f"{name}.npz")

    def f(y):
        return problem.constraint(y)[1]

    try:
        detected = asdex.jacobian_sparsity(f, problem.y0.shape)
    except (NotImplementedError, IndexError, ValueError) as exc:
        pytest.xfail(f"asdex internal error for {name}: {exc}")

    _assert_superset(
        detected.todense().astype(bool),
        gt.todense().astype(bool),
        name,
        "jacobian_ineq",
    )
    _check_baseline(detected.nnz, name, "jacobian_ineq")
